apiVersion: v1
kind: Service
metadata:
  name: timetable-app-service
  namespace: default  # Ensure this matches the namespace where the app is deployed
spec:
  selector:
    app: timetable-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
